from enum import Enum

class PhysicalQuantities(Enum):
    ELECTRICAL_CURRENT = (1,)
    ELECTRICAL_CHARGE = (2,)
    ELECTRICAL_ENERGY = (3,)
    ELECTRICAL_POWER = (4,)
    ELECTRICAL_APPARENT_POWER = (5,)
    ELECTRICAL_REACTIVE_POWER = (6,)
    POTENTIAL_DIFFERENCE = (7,)
    POWER_FACTOR = (8,)
    LENGTH = (9,)
    DISTANCE = (10,)
    SPEED = (11,)
    ANGLE = (12,)
    ANGULAR_VELOCITY = (13,)
    VOLUME = (14,)
    VOLUMETRIC_FLOW = (15,)
    MAGNETIC_FIELD = (16,)
    FREQUENCY = (17,)
    DATE = (18,)
    TIME = (19,)
    DURATION = (20,)
    GEOGRAPHICAL_LATITUDE = (21,)
    GEOGRAPHICAL_LONGITUDE = (22,)
    TEMPERATURE = (23,)
    PRESSURE = (24,)
    PRESSURE_RATE = (25,)
    CONCENTRATION = (26,)
    DIMENSIONLESS_RATIO = (27,)
    SQUARE_ROOT_LENGTH = (28,)
    SIGNAL_STRENGTH = (29,)
    SIGNAL_TO_NOISE_RATIO = (30,)

class FieldTypes(Enum):
    NUMBER = (1,)
    FLOAT = (2,)
    DECIMAL = (3,)
    LOOKUP = (4,)
    INDIRECT_LOOKUP = (5,)
    BITLOOKUP = (6,)
    DYNAMIC_FIELD_KEY = (7,)
    DYNAMIC_FIELD_LENGTH = (8,)
    DYNAMIC_FIELD_VALUE = (9,)
    TIME = (10,)
    DURATION = (11,)
    DATE = (12,)
    PGN = (13,)
    ISO_NAME = (14,)
    STRING_FIX = (15,)
    STRING_LZ = (16,)
    STRING_LAU = (17,)
    BINARY = (18,)
    RESERVED = (19,)
    SPARE = (20,)
    MMSI = (21,)
    VARIABLE = (22,)
    FIELD_INDEX = (23,)
    ADDRESS = (24,)

ManufacturerCodes: list[str]
