repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--line-length, "127"]
        exclude: ^nmea2000/(pgns|consts)\.py$
      - id: ruff-format
        exclude: ^nmea2000/(pgns|consts)\.py$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^nmea2000/(pgns|consts)\.py$
      - id: end-of-file-fixer
        exclude: ^nmea2000/(pgns|consts)\.py$
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: check-generated-files
        name: check generated files are up to date
        language: python
        entry: python check_generated_files.py
        files: ^(canboat\.json|canboat2python\.py|python\.PGNs\.j2|python\.consts\.j2)$
        pass_filenames: false
        additional_dependencies: [jinja2]
