"""Generate the native-unit table from the canboat JSON schema.

Everything else nmea2000 knows about PGNs comes from the canboat crate at run
time; this table records where canboat.json's units differ from the crate's.
"""

import json
import os

with open("canboat.json", encoding="utf-8") as f:
    json_data = json.load(f)


def native_units() -> dict[tuple[str, str], tuple[str | None, float | None, int]]:
    """Fields whose canboat.json unit differs from the canboat crate's SI unit.

    nmea2000 reports values in canboat.json's own units (%, rpm, L, kWh, deg,
    ...), but the canboat crate decodes into strict SI (ratio, Hz, m3, J, rad).
    For each field where the two differ, record the JSON unit, resolution and
    offset so the backend can rescale the wire value.
    """
    from nmea2000 import _canboat as canboat  # pylint: disable=import-outside-toplevel

    db = canboat.Database()
    json_fields = {
        (pgn["Id"], field["Id"]): field
        for pgn in json_data["PGNs"]
        for field in pgn.get("Fields", [])
    }
    table = {}
    for pgn in db.pgns():
        for field in pgn.fields:
            json_field = json_fields.get((pgn.id, field.id))
            if json_field is None or json_field.get("Unit") == field.unit:
                continue
            table[(pgn.id, field.id)] = (
                json_field.get("Unit"),
                json_field.get("Resolution"),
                json_field.get("Offset", 0),
            )
    return table


units_table = native_units()
with open(os.path.join("nmea2000", "native_units.py"), "w", encoding="utf-8") as f:
    f.write('"""Generated by canboat2python.py from canboat.json. Do not edit."""\n\n')
    f.write(f"CANBOAT_VERSION = {json_data['Version']!r}\n\n")
    f.write("# (pgn id, field id) -> (canboat.json unit, resolution, offset)\n")
    f.write(
        "NATIVE_UNITS: dict[tuple[str, str], tuple[str | None, float | None, int]] = {\n"
    )
    f.writelines(
        f"    {key!r}: {value!r},\n" for key, value in sorted(units_table.items())
    )
    f.write("}\n")

print("Python code generated successfully!")
